<a href="https://colab.research.google.com/github/SaakshiNarula/AccentClustering/blob/master/Untitled18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#to be restructured

import json
file_path = 'stats250su2020Chapter_4_Video_3_Uniform.json'
with open(file_path) as json_file:
  document = json.load(json_file, strict=False)
  doc3 = document['results']['transcripts'][0]['transcript']


file_path = 'stats250su2020Chapter_4_Video_2_Binomial.json'
with open(file_path) as json_file:
  document = json.load(json_file, strict=False)
  doc2 = document['results']['transcripts'][0]['transcript']

file_path = 'stats250su2020Chapter_4_Video_1_General_Discrete_Model (1).json'
with open(file_path) as json_file:
  document = json.load(json_file, strict=False)
  doc1 = document['results']['transcripts'][0]['transcript']

In [ ]:
import nltk
nltk.download('punkt')
doc1 = nltk.sent_tokenize(doc1)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
# stats250 gold standard
txt_keywds = ['Sample',
'Population data',
'Sample data',
'parameter',
'statistic',
'categorical variable',
'quantitative variable',
'ANALYSIS OF VARIANCE',
'ANOVA',
'two independent samples POOLED t-test',
'One-way ANOVA',
'random sample',
'independent',
'a normal distribution',
'confidence interval',
'test of hypotheses',
'standard deviation',
'Sum of Squares',
'Two-Way ANOVA',
'scatterplot',
'overall form',
'direction of association',
'strength of association',
'any deviations from the overall form',
'correlation coefficient r',
'least squares regression line',
'Slope',
'y-intercept',
'Estimated',
'residual',
'sum of squared errors',
'total variation',
't-Test',
'F Test',
'Explanatory',
'Response',
'Confounding',
'Reject H0',
'Fail to reject H0',
'Goodness of Fit Test:',
'Test of Homogeneity',
'Test of Independence',
'chi-square distribution',
'null hypothesis',
'Cross-Product Rule',
'p-value',
'Confidence Interval Estimation',
'Hypothesis Testing',
'Independent',
'Identically distributed',
'Randomized Study',
'Placebo-Controlled',
'Active-Controlled',
'Blinding',
'Completely Randomized Design',
'Randomized Block Design',
'Selection bias',
'Response bias',
'Nonresponse bias',
'Observational Study',
'Experiment',
'parameter',
'statistic',
'Mutually Exclusive',
'Disjoint',
'independent',
'multiplication rule for independent events',
'random variable',
'discrete random variable',
'continuous random variable',
'Binomial',
'cumulative distribution function',
'probability mass function',
'expected value',
'Binomial Random Variables',
'binomial Experiment',
'binomial distribution',
'density curve',
'Expected Value or Mean',
'Normal Random Variables',
'Normal Curve',
'z-score',
'Normal Approximation to the Binomial Distribution',
'standard error',
'Conservative Confidence Interval',
'Choosing a Sample Size for a Survey',
'alternative hypothesis',
'one-sided or',
'one-tailed hypothesis test',
'two-sided or two-tailed hypothesis test',
'power of the test',
'Type 1 error',
'Type 2 error',
'Decision Rule',
'Distribution of the Difference in Two (Independent) Sample Proportions',
'Standard Error of the Difference in Sample Proportions',
'Large Sample Z Test',
'Population',
'Statistic',
'sampling distribution of a statistic',
'confidence level',
'Population parameter',
'Sample estimate',
'Mean of Paired Differences',
'mean of the population of differences',
'Sample Mean Difference',
'Population Mean Difference',
'Paired t-Test',
'Assumptions',
'Unpooled',
'Pooled Approach',
'Pooled standard deviation',
'boxplots',
'Pooled standard error']

In [ ]:
dictOfWords = { i : 0 for i in txt_keywds}

In [ ]:
for sent in doc1:
  for word in txt_keywds:
    if word in sent:
      dictOfWords[word]+=1

In [ ]:
dictOfWords

{'ANALYSIS OF VARIANCE': 0,
 'ANOVA': 0,
 'Active-Controlled': 0,
 'Assumptions': 0,
 'Binomial': 0,
 'Binomial Random Variables': 0,
 'Blinding': 0,
 'Choosing a Sample Size for a Survey': 0,
 'Completely Randomized Design': 0,
 'Confidence Interval Estimation': 0,
 'Confounding': 0,
 'Conservative Confidence Interval': 0,
 'Cross-Product Rule': 0,
 'Decision Rule': 0,
 'Disjoint': 0,
 'Distribution of the Difference in Two (Independent) Sample Proportions': 0,
 'Estimated': 0,
 'Expected Value or Mean': 0,
 'Experiment': 0,
 'Explanatory': 0,
 'F Test': 0,
 'Fail to reject H0': 0,
 'Goodness of Fit Test:': 0,
 'Hypothesis Testing': 0,
 'Identically distributed': 0,
 'Independent': 0,
 'Large Sample Z Test': 0,
 'Mean of Paired Differences': 0,
 'Mutually Exclusive': 0,
 'Nonresponse bias': 0,
 'Normal Approximation to the Binomial Distribution': 0,
 'Normal Curve': 0,
 'Normal Random Variables': 0,
 'Observational Study': 0,
 'One-way ANOVA': 0,
 'Paired t-Test': 0,
 'Placebo-Controlled': 0,
 'Pooled Approach': 0,
 'Pooled standard deviation': 0,
 'Pooled standard error': 0,
 'Population': 0,
 'Population Mean Difference': 0,
 'Population data': 0,
 'Population parameter': 0,
 'Randomized Block Design': 0,
 'Randomized Study': 0,
 'Reject H0': 0,
 'Response': 0,
 'Response bias': 0,
 'Sample': 0,
 'Sample Mean Difference': 0,
 'Sample data': 0,
 'Sample estimate': 0,
 'Selection bias': 0,
 'Slope': 0,
 'Standard Error of the Difference in Sample Proportions': 0,
 'Statistic': 0,
 'Sum of Squares': 0,
 'Test of Homogeneity': 0,
 'Test of Independence': 0,
 'Two-Way ANOVA': 0,
 'Type 1 error': 0,
 'Type 2 error': 0,
 'Unpooled': 0,
 'a normal distribution': 0,
 'alternative hypothesis': 0,
 'any deviations from the overall form': 0,
 'binomial Experiment': 0,
 'binomial distribution': 0,
 'boxplots': 0,
 'categorical variable': 0,
 'chi-square distribution': 0,
 'confidence interval': 0,
 'confidence level': 0,
 'continuous random variable': 0,
 'correlation coefficient r': 0,
 'cumulative distribution function': 2,
 'density curve': 0,
 'direction of association': 0,
 'discrete random variable': 0,
 'expected value': 6,
 'independent': 0,
 'least squares regression line': 0,
 'mean of the population of differences': 0,
 'multiplication rule for independent events': 0,
 'null hypothesis': 0,
 'one-sided or': 0,
 'one-tailed hypothesis test': 0,
 'overall form': 0,
 'p-value': 0,
 'parameter': 4,
 'power of the test': 0,
 'probability mass function': 0,
 'quantitative variable': 3,
 'random sample': 1,
 'random variable': 16,
 'residual': 0,
 'sampling distribution of a statistic': 0,
 'scatterplot': 0,
 'standard deviation': 3,
 'standard error': 0,
 'statistic': 0,
 'strength of association': 0,
 'sum of squared errors': 0,
 't-Test': 0,
 'test of hypotheses': 0,
 'total variation': 0,
 'two independent samples POOLED t-test': 0,
 'two-sided or two-tailed hypothesis test': 0,
 'y-intercept': 0,
 'z-score': 0}

In [ ]:
import pandas as pd
Q = pd.read_excel('stats250_problemroulette_Q.xlsx')
A = pd.read_excel('stats250_problemroulette_ANS.xlsx')
Q_numbers = pd.read_csv('stats250_problemroulette_question_numbers.csv')
Chapter = pd.read_csv('stats250_problemroulette_chapter.csv')

In [ ]:
#chapter 4 Q numbers
ref_id = int(Chapter[Chapter['order'] == 4]['id'])
q_numbers = list(Q_numbers[Q_numbers['topic_id'] == ref_id]['question_id'])
q_numbers

[7793,
 7794,
 7802,
 7804,
 7805,
 7820,
 7853,
 7854,
 7855,
 7863,
 7864,
 7865,
 7866,
 7867,
 7873,
 7874,
 7954,
 7960,
 7961,
 7978,
 7979,
 7980,
 7983,
 7984,
 7992,
 7993,
 8071,
 8073,
 8075,
 8076,
 8077,
 8078,
 8082,
 8083,
 8084,
 8136,
 8137,
 9993,
 9994,
 9995,
 10893,
 10911,
 10912,
 10914,
 10915,
 10917,
 16416,
 16421,
 16497,
 16695,
 18457,
 18482,
 18498,
 18509,
 18513,
 18514,
 18515,
 18528,
 18531,
 18555,
 18556,
 18562,
 18576,
 18580,
 18593,
 18611,
 18624,
 18628,
 18636,
 18647,
 18659,
 18660,
 18674,
 18706,
 18724,
 18737,
 18746,
 18750,
 18760,
 18766,
 18772,
 18783,
 18795,
 18797,
 18800,
 18964,
 18977,
 18993,
 19006,
 19013,
 19021,
 19036,
 19039,
 19052,
 19055,
 19074,
 19075,
 19076,
 19082,
 19093,
 19098,
 19099,
 19110,
 19142,
 19183,
 19184,
 19187,
 19188,
 19192,
 19208,
 19210,
 19219,
 19222,
 19237,
 19257,
 19272,
 19276,
 19281,
 19287,
 19304,
 19308,
 19311,
 19313,
 19327,
 19352,
 19356,
 19357,
 19380,
 19410,
 19412,
 19422,
 19428,
 19439,
 19467,
 19484,
 19490,
 19520,
 19533,
 19544,
 19612,
 19621,
 19662,
 19668,
 19688,
 19699,
 19705,
 19706,
 19788,
 19790,
 19844,
 19852,
 19856,
 19943,
 19946,
 19964,
 19979,
 19999,
 20027,
 20028,
 20047,
 20055,
 20061,
 20196]

In [ ]:
chp4_questions = Q[Q['id'].isin(q_numbers)]

In [ ]:
updated_dict = {}
for (key, value) in dictOfWords.items():
  if value != 0:
    updated_dict[key] =value
updated_dict_keys = [*updated_dict]

In [ ]:
updated_dict_keys
bank = pd.DataFrame()
for i in range(len(chp4_questions)):
  for key in updated_dict_keys:
    if key in chp4_questions.iloc[i]['text']:
     
      bank = bank.append(chp4_questions.iloc[i])
      break
bank

      accuracy  ...  title
0         36.0  ...    1.0
1         73.0  ...    1.0
9         71.0  ...    0.0
11        94.0  ...    0.0
12        89.0  ...    0.0
...        ...  ...    ...
1632      70.0  ...    0.0
1640      78.0  ...    0.0
1740      65.0  ...    0.0
1778      80.0  ...    1.0
1779      53.0  ...    1.0

[91 rows x 23 columns]

In [ ]:
#next- randomly select a question from Q and its corresponding answer from A